version: '3'

services:
  bitstock:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5003:8000"
    restart: always
    container_name: "bitstock-container"
    environment:
      - ALLOWED_HOSTS= localhost 127.0.0.1
    volumes:
      - .:/code
      - ./sqlite:/sqlite
      - ./api/static:/api/static