# Generated by Django 5.0.3 on 2024-04-12 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=56, unique=True)),
                ('tg_id', models.CharField(default='no-auth', max_length=56)),
                ('name', models.CharField(default='no-auth', max_length=56)),
                ('stoks_id', models.JSONField(default=None)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
