# Generated by Django 5.0.3 on 2024-04-12 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramusers',
            name='stoks_id',
            field=models.JSONField(),
        ),
    ]
