# Generated by Django 5.0.4 on 2024-04-20 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_stoks_id_telegramusers_stocks_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orgs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=56)),
                ('boss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.telegramusers')),
            ],
        ),
    ]
