# Generated by Django 5.0.4 on 2024-04-21 12:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_orgs'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orgs',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='orgs',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
