# Generated by Django 5.0.4 on 2024-04-24 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_orgs_boss_orgs_boss_tg_orgs_workers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramusers',
            name='stocks_id',
        ),
    ]
