# Generated by Django 5.0.4 on 2024-04-30 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_categories_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='org',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, to='api.orgs'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='org',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.orgs'),
            preserve_default=False,
        ),
    ]
