# Generated by Django 5.0.4 on 2024-04-30 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_categories_org_products_org'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='name',
            field=models.CharField(default='no-name', max_length=56),
        ),
    ]
